//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsgReader.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageConsts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageConsts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsgReader.Localization.LanguageConsts", typeof(LanguageConsts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string AppointmentAttachmentsLabel {
            get {
                return ResourceManager.GetString("AppointmentAttachmentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string AppointmentCategoriesLabel {
            get {
                return ResourceManager.GetString("AppointmentCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string AppointmentClientIntentCanceledText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentCanceledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acting as delegate for the organizer of the meeting.
        /// </summary>
        internal static string AppointmentClientIntentDelegateText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentDelegateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted exception with no response.
        /// </summary>
        internal static string AppointmentClientIntentDeletedExceptionWithNoResponseText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentDeletedExceptionWithNoResponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted meeting with no response.
        /// </summary>
        internal static string AppointmentClientIntentDeletedWithNoResponseText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentDeletedWithNoResponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string AppointmentClientIntentExceptionCanceledText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentExceptionCanceledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting status.
        /// </summary>
        internal static string AppointmentClientIntentLabel {
            get {
                return ResourceManager.GetString("AppointmentClientIntentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer of the meeting.
        /// </summary>
        internal static string AppointmentClientIntentManagerText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentManagerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified end time.
        /// </summary>
        internal static string AppointmentClientIntentModifiedEndTimeText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentModifiedEndTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified location.
        /// </summary>
        internal static string AppointmentClientIntentModifiedLocationText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentModifiedLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified start time.
        /// </summary>
        internal static string AppointmentClientIntentModifiedStartTimeText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentModifiedStartTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string AppointmentClientIntentRespondedAcceptText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentRespondedAcceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string AppointmentClientIntentRespondedDeclineText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentRespondedDeclineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception declined.
        /// </summary>
        internal static string AppointmentClientIntentRespondedExceptionDeclineText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentRespondedExceptionDeclineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative.
        /// </summary>
        internal static string AppointmentClientIntentRespondedTentativeText {
            get {
                return ResourceManager.GetString("AppointmentClientIntentRespondedTentativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string AppointmentEndDateLabel {
            get {
                return ResourceManager.GetString("AppointmentEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string AppointmentLocationLabel {
            get {
                return ResourceManager.GetString("AppointmentLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory participants.
        /// </summary>
        internal static string AppointmentMandatoryParticipantsLabel {
            get {
                return ResourceManager.GetString("AppointmentMandatoryParticipantsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional participants.
        /// </summary>
        internal static string AppointmentOptionalParticipantsLabel {
            get {
                return ResourceManager.GetString("AppointmentOptionalParticipantsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        internal static string AppointmentOrganizerLabel {
            get {
                return ResourceManager.GetString("AppointmentOrganizerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string AppointmentReccurenceTypeDailyText {
            get {
                return ResourceManager.GetString("AppointmentReccurenceTypeDailyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string AppointmentReccurenceTypeMonthlyText {
            get {
                return ResourceManager.GetString("AppointmentReccurenceTypeMonthlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string AppointmentReccurenceTypeNoneText {
            get {
                return ResourceManager.GetString("AppointmentReccurenceTypeNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string AppointmentReccurenceTypeWeeklyText {
            get {
                return ResourceManager.GetString("AppointmentReccurenceTypeWeeklyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string AppointmentReccurenceTypeYearlyText {
            get {
                return ResourceManager.GetString("AppointmentReccurenceTypeYearlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence patern type.
        /// </summary>
        internal static string AppointmentRecurrencePaternLabel {
            get {
                return ResourceManager.GetString("AppointmentRecurrencePaternLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence patern.
        /// </summary>
        internal static string AppointmentRecurrenceTypeLabel {
            get {
                return ResourceManager.GetString("AppointmentRecurrenceTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string AppointmentResourcesLabel {
            get {
                return ResourceManager.GetString("AppointmentResourcesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string AppointmentStartDateLabel {
            get {
                return ResourceManager.GetString("AppointmentStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string AppointmentSubjectLabel {
            get {
                return ResourceManager.GetString("AppointmentSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        internal static string AssistantLabel {
            get {
                return ResourceManager.GetString("AssistantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        internal static string AssistantTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("AssistantTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager.
        /// </summary>
        internal static string BeeperTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("BeeperTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string BirthdayLabel {
            get {
                return ResourceManager.GetString("BirthdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business fax.
        /// </summary>
        internal static string BusinessFaxNumberLabel {
            get {
                return ResourceManager.GetString("BusinessFaxNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business 2.
        /// </summary>
        internal static string BusinessTelephoneNumber2Label {
            get {
                return ResourceManager.GetString("BusinessTelephoneNumber2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string BusinessTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("BusinessTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback.
        /// </summary>
        internal static string CallbackTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("CallbackTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string CarTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("CarTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string CellularTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("CellularTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string CompanyLabel {
            get {
                return ResourceManager.GetString("CompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company main phone.
        /// </summary>
        internal static string CompanyMainTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("CompanyMainTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd-yyyy.
        /// </summary>
        internal static string DataFormat {
            get {
                return ResourceManager.GetString("DataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string DataFormatWithTime {
            get {
                return ResourceManager.GetString("DataFormatWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string DateDifferenceDaysText {
            get {
                return ResourceManager.GetString("DateDifferenceDaysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string DateDifferenceDayText {
            get {
                return ResourceManager.GetString("DateDifferenceDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string DateDifferenceHoursText {
            get {
                return ResourceManager.GetString("DateDifferenceHoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string DateDifferenceHourText {
            get {
                return ResourceManager.GetString("DateDifferenceHourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string DateDifferenceMinutesText {
            get {
                return ResourceManager.GetString("DateDifferenceMinutesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string DateDifferenceMinuteText {
            get {
                return ResourceManager.GetString("DateDifferenceMinuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string DateDifferenceMonthsText {
            get {
                return ResourceManager.GetString("DateDifferenceMonthsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string DateDifferenceMonthText {
            get {
                return ResourceManager.GetString("DateDifferenceMonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string DateDifferenceSecondsText {
            get {
                return ResourceManager.GetString("DateDifferenceSecondsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string DateDifferenceSecondText {
            get {
                return ResourceManager.GetString("DateDifferenceSecondText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        internal static string DateDifferenceWeeksText {
            get {
                return ResourceManager.GetString("DateDifferenceWeeksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        internal static string DateDifferenceWeekText {
            get {
                return ResourceManager.GetString("DateDifferenceWeekText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string DateDifferenceYearsText {
            get {
                return ResourceManager.GetString("DateDifferenceYearsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string DateDifferenceYearText {
            get {
                return ResourceManager.GetString("DateDifferenceYearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DepartmentLabel {
            get {
                return ResourceManager.GetString("DepartmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string DisplayNameLabel {
            get {
                return ResourceManager.GetString("DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail display as.
        /// </summary>
        internal static string Email1DisplayNameLabel {
            get {
                return ResourceManager.GetString("Email1DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email1EmailAddressLabel {
            get {
                return ResourceManager.GetString("Email1EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 2 display as.
        /// </summary>
        internal static string Email2DisplayNameLabel {
            get {
                return ResourceManager.GetString("Email2DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 2.
        /// </summary>
        internal static string Email2EmailAddressLabel {
            get {
                return ResourceManager.GetString("Email2EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 3 display as.
        /// </summary>
        internal static string Email3DisplayNameLabel {
            get {
                return ResourceManager.GetString("Email3DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 3.
        /// </summary>
        internal static string Email3EmailAddressLabel {
            get {
                return ResourceManager.GetString("Email3EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string EmailAttachmentsLabel {
            get {
                return ResourceManager.GetString("EmailAttachmentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC.
        /// </summary>
        internal static string EmailBccLabel {
            get {
                return ResourceManager.GetString("EmailBccLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string EmailCategoriesLabel {
            get {
                return ResourceManager.GetString("EmailCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        internal static string EmailCcLabel {
            get {
                return ResourceManager.GetString("EmailCcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string EmailFollowUpCompletedText {
            get {
                return ResourceManager.GetString("EmailFollowUpCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string EmailFollowUpFlag {
            get {
                return ResourceManager.GetString("EmailFollowUpFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow up.
        /// </summary>
        internal static string EmailFollowUpLabel {
            get {
                return ResourceManager.GetString("EmailFollowUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow up status.
        /// </summary>
        internal static string EmailFollowUpStatusLabel {
            get {
                return ResourceManager.GetString("EmailFollowUpStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string EmailFromLabel {
            get {
                return ResourceManager.GetString("EmailFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on behalf of.
        /// </summary>
        internal static string EmailOnBehalfOf {
            get {
                return ResourceManager.GetString("EmailOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent on.
        /// </summary>
        internal static string EmailSentOnLabel {
            get {
                return ResourceManager.GetString("EmailSentOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed by.
        /// </summary>
        internal static string EmailSignedBy {
            get {
                return ResourceManager.GetString("EmailSignedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string EmailSignedByOn {
            get {
                return ResourceManager.GetString("EmailSignedByOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string EmailSubjectLabel {
            get {
                return ResourceManager.GetString("EmailSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string EmailToLabel {
            get {
                return ResourceManager.GetString("EmailToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string FunctionLabel {
            get {
                return ResourceManager.GetString("FunctionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string GivenNameLabel {
            get {
                return ResourceManager.GetString("GivenNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home address.
        /// </summary>
        internal static string HomeAddressLabel {
            get {
                return ResourceManager.GetString("HomeAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home fax.
        /// </summary>
        internal static string HomeFaxNumberLabel {
            get {
                return ResourceManager.GetString("HomeFaxNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home 2.
        /// </summary>
        internal static string HomeTelephoneNumber2Label {
            get {
                return ResourceManager.GetString("HomeTelephoneNumber2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("HomeTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page.
        /// </summary>
        internal static string HtmlLabel {
            get {
                return ResourceManager.GetString("HtmlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string ImportanceHighText {
            get {
                return ResourceManager.GetString("ImportanceHighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        internal static string ImportanceLabel {
            get {
                return ResourceManager.GetString("ImportanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string ImportanceLowText {
            get {
                return ResourceManager.GetString("ImportanceLowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImportanceNormalText {
            get {
                return ResourceManager.GetString("ImportanceNormalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM address.
        /// </summary>
        internal static string InstantMessagingAddressLabel {
            get {
                return ResourceManager.GetString("InstantMessagingAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDN.
        /// </summary>
        internal static string ISDNNumberLabel {
            get {
                return ResourceManager.GetString("ISDNNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameless.
        /// </summary>
        internal static string NameLessFileName {
            get {
                return ResourceManager.GetString("NameLessFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other address.
        /// </summary>
        internal static string OtherAddressLabel {
            get {
                return ResourceManager.GetString("OtherAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other fax.
        /// </summary>
        internal static string OtherFaxLabel {
            get {
                return ResourceManager.GetString("OtherFaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("OtherTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other fax.
        /// </summary>
        internal static string PrimaryFaxNumberLabel {
            get {
                return ResourceManager.GetString("PrimaryFaxNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary phone.
        /// </summary>
        internal static string PrimaryTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("PrimaryTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string ProfessionLabel {
            get {
                return ResourceManager.GetString("ProfessionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        internal static string RadioTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("RadioTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse/Partner.
        /// </summary>
        internal static string SpouseNameLabel {
            get {
                return ResourceManager.GetString("SpouseNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string StickyNoteDateLabel {
            get {
                return ResourceManager.GetString("StickyNoteDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string SurNameLabel {
            get {
                return ResourceManager.GetString("SurNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual work.
        /// </summary>
        internal static string TaskActualEffortLabel {
            get {
                return ResourceManager.GetString("TaskActualEffortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing information.
        /// </summary>
        internal static string TaskBillingInformationLabel {
            get {
                return ResourceManager.GetString("TaskBillingInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string TaskCompanyLabel {
            get {
                return ResourceManager.GetString("TaskCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string TaskContactsLabel {
            get {
                return ResourceManager.GetString("TaskContactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed on.
        /// </summary>
        internal static string TaskDateCompleted {
            get {
                return ResourceManager.GetString("TaskDateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string TaskDueDateLabel {
            get {
                return ResourceManager.GetString("TaskDueDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total work.
        /// </summary>
        internal static string TaskEstimatedEffortLabel {
            get {
                return ResourceManager.GetString("TaskEstimatedEffortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        internal static string TaskMileageLabel {
            get {
                return ResourceManager.GetString("TaskMileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string TaskOwnerLabel {
            get {
                return ResourceManager.GetString("TaskOwnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage complete.
        /// </summary>
        internal static string TaskPercentageCompleteLabel {
            get {
                return ResourceManager.GetString("TaskPercentageCompleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested by.
        /// </summary>
        internal static string TaskRequestedByLabel {
            get {
                return ResourceManager.GetString("TaskRequestedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string TaskStartDateLabel {
            get {
                return ResourceManager.GetString("TaskStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string TaskStatusCompleteText {
            get {
                return ResourceManager.GetString("TaskStatusCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        internal static string TaskStatusInProgressText {
            get {
                return ResourceManager.GetString("TaskStatusInProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TaskStatusLabel {
            get {
                return ResourceManager.GetString("TaskStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        internal static string TaskStatusNotStartedText {
            get {
                return ResourceManager.GetString("TaskStatusNotStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string TaskStatusWaitingText {
            get {
                return ResourceManager.GetString("TaskStatusWaitingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string TaskSubjectLabel {
            get {
                return ResourceManager.GetString("TaskSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telex.
        /// </summary>
        internal static string TelexNumberLabel {
            get {
                return ResourceManager.GetString("TelexNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTY/TDD phone.
        /// </summary>
        internal static string TextTelephoneLabel {
            get {
                return ResourceManager.GetString("TextTelephoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary.
        /// </summary>
        internal static string WeddingAnniversaryLabel {
            get {
                return ResourceManager.GetString("WeddingAnniversaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address.
        /// </summary>
        internal static string WorkAddressLabel {
            get {
                return ResourceManager.GetString("WorkAddressLabel", resourceCulture);
            }
        }
    }
}
